### ISSUE TITLE
Change info about office location

### ISSUE THREAD

**Issue by KilinMikhail** [fs/flatstack-warsaw#61]
1. remove Russia
2. rename Kazan office to Antalya office

[Внести_правки_в_варшавский_лендинг_.pdf](https://github.com/fs/flatstack-warsaw/files/9282229/_._._._._.pdf)

**Comment by braska** [comment]
> to Warsaw → to Warsaw/Turkey
Это будет выглядеть очень странно. Всё таки лендинг на домене warsaw.flatstack.com. Нужно отдельно обсуждать.

**Comment by DanilAgafonov** [comment]
> to Warsaw → to Warsaw/Turkey

Это будет выглядеть очень странно. Всё таки лендинг на домене warsaw.flatstack.com. Нужно отдельно обсуждать.

**Comment by DanilAgafonov** [comment]
@KilinMikhail 6 и 7 сделай плиз отдельными issue и следовательно отдельными PR.

И тогда задачу можно будет переименовать и назвать например: "Change info about office location"

**Comment by KilinMikhail** [comment]
@DanilAgafonov The doc says to remove the Kazan office info and add a Turkish office info, is it necessary to search for a photo for the Turkish office? In addition, there was an option to update the photo for Kazan and rename it to global, is there a solution for this?

**Comment by DanilAgafonov** [comment]
@KilinMikhail It was never discussed with me. I hear about it for the first time. So I can't make any decisions here. But I think it is okay to to leave photo from Kazan and change text. I am not sure about photo from Turkey. I don't think that it is possible to get such photo. Please discuss it with Zee.

**Comment by KilinMikhail** [comment]
@DanilAgafonov Zee told me that we need to add do this change (to Warsaw → to Warsaw/Turkey). And if the domain is a problem then we should to change subdomain
